---
title: "Rock Gym Daily Operations"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "white"
      fg: "black" 
      primary: "#69bf86"
      secondary: "#74c476"
      highlight_font: Ubuntu
      base_font:
        google: Fira Sans
      code_font:
        google: JetBrains Mono
      navbar_bg: "#69bf86"
      body_color: "#69bf86"
      accordion_button_active_bg: "#69bf86"
      accordion_button_active_color: 'black'
      bs_accordion_color: "#69bf86"
      light: "white"
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(bslib)
library(tidyverse)
library(htmltools)
library(bslib)
library(bsicons)
library(summarywidget)
library(plotly)
library(lubridate)
library(scales)
library(crosstalk)

knitr::opts_chunk$set(warning = F,message = F)
```

```{r}
valueBoxSummaryWidget <- function (value, caption = NULL, icon = NULL, color = NULL, href = NULL) 
{
  if (!is.null(color) && color %in% c("primary", "info", 
                                      "success", "warning", "danger")) 
    color <- paste0("bg-", color)
  valueOutput <- tags$span(class = "value-summarywidget-output", `data-caption` = caption, 
                           `data-icon` = icon, `data-color` = color, 
                           `data-href` = href, value)
  hasPrefix <- function(x, prefix) {
    if (!is.null(x)) 
      grepl(paste0("^", prefix), x)
    else FALSE
  }
  fontAwesome <- hasPrefix(icon, "fa")
  ionicons <- hasPrefix(icon, "ion")
  deps <- flexdashboard:::html_dependencies_fonts(fontAwesome, ionicons)
  if (length(deps) > 0) 
    valueOutput <- attachDependencies(valueOutput, deps)
  valueOutput
}
```

```{r global read_in_data, include = F}

rock_visit_dat = read_csv('F:/R Projects/MadsenData_data/data/rock_visit_data.csv')

rock_visit_dat = rock_visit_dat %>% 
  mutate(days_in_month = case_when(
    month == "Jan" ~ 31,
    month == "Feb" ~ 28,
    month == "Mar" ~ 31,
    month == "Apr" ~ 30,
    month == "May" ~ 31,
    month == "Jun" ~ 30
  )) %>% 
  group_by(month) %>% 
  group_split() %>% 
  map( ~ {
    crossing(.x,1:.x$days_in_month) %>% 
      distinct() %>% 
      mutate(drop_ins = drop_ins +sample(c(-3:3,1)),
             members = members + sample(c(-3:3,1))) %>% 
      mutate(visits = drop_ins + members)
  }) %>% 
  bind_rows() %>% 
  mutate(month = factor(month, levels = c("Jan","Feb","Mar","Apr","May","Jun")))

rock_visit_dat = rock_visit_dat %>% 
  select(-visits) %>% 
  rename(my_month = month) %>% 
  pivot_longer(c("drop_ins","members"), names_to = 'membership_type', values_to = 'visits') %>% 
  mutate(membership_type = case_when(
    membership_type == "drop_ins" ~ "Drop-ins",
    T ~ "Members"
  )) %>% 
  mutate(hour_of_day = as.numeric(str_remove(hour_of_day, "H"))) %>% 
  mutate(day_as_number = case_when(
    day_of_week == "Monday" ~ 1,
    day_of_week == "Tuesday" ~ 2,
    day_of_week == "Wednesday" ~ 3,
    day_of_week == "Thursday" ~ 4,
    day_of_week == "Friday" ~ 5,
    day_of_week == "Saturday" ~ 6,
    day_of_week == "Sunday" ~ 7
  )) %>% 
  mutate(month_as_number = case_when(
    my_month == "Jan" ~ 1,
    my_month == "Feb" ~ 2,
    my_month == "Mar" ~ 3,
    my_month == "Apr" ~ 4,
    my_month == "May" ~ 5,
    my_month == "Jun" ~ 6,
  )) %>% 
  mutate(day_of_week = factor(day_of_week, levels = levels(wday(1,label = T,abbr=F,week_start = 1)))) %>% 
  mutate(my_month = factor(my_month, levels = c("Jan","Feb","Mar","Apr","May","Jun")))
```


```{r make_shared_datasets}

visits_by_hour = rock_visit_dat %>% 
  group_by(hour_of_day, membership_type, location) %>% 
  summarise(mean_visits = round(mean(visits),1))

visits_by_day = rock_visit_dat %>% 
  group_by(day_as_number, membership_type, location) %>% 
  summarise(mean_visits = round(mean(visits),1))

visits_by_month = rock_visit_dat %>% 
  group_by(month_as_number, membership_type, location) %>% 
  summarise(mean_visits = round(mean(visits),1))

visitsHour = SharedData$new(visits_by_hour)
visitsDay = SharedData$new(visits_by_day)
visitsMonth = SharedData$new(visits_by_month)

# RockVisitDat = SharedData$new(rock_visit_dat)
```

```{r design_filters_and_buttons}
hour_filter = filter_slider('hour_slider', 'Hours to Include', visitsHour, ~hour_of_day, min = 6, max = 22)

day_filter = filter_slider('day_slider', 'Days to Include',  visitsDay, ~day_as_number, min = 1, max = 7)

month_filter = filter_slider('day_slider',
                             'Months to Include',
                             visitsMonth,
                             ~month_as_number,
                             min = 2,
                             max = 6)

# location_select = filter_select('loc_filter', "Location", visitsHour, ~location)
# 
# membership_type_select = filter_select("memb_type", "Membership Type", visitsHour, ~membership_type)
```

```{r plotting_functions}
average_barplot_by_membership_type = function(reactive_data, x_var = NULL, y_var = NULL, grouper = NULL, xlabel = "X", ylabel = "Y", color_set = "Dark2"){
  
  p = plot_ly(data = reactive_data,
              x = ~.data[[x_var]], 
              y = ~.data[[y_var]],
              color = ~membership_type,
              colors = color_set
              # type = 'bar', 
              ) %>% 
    group_by(!!sym(grouper)) %>% 
    add_bars(hoverinfo = 'text',
             hovertext = ~paste0(mean_visits, 
                                  " visits on average")) %>% 
  #   layout(
  #         transforms = list(
  #           list(
  #             type = 'aggregate',
  #             groups = ~.data[[grouper]],
  #             aggregations = list(
  #               list(
  #                 target = 'y',
  #                 func = 'mean',
  #                 enabled = T
  #               )
  #             )
  #           )
  #         )
  # ) %>%
  layout(barmode = 'stack',
         showlegend = F,
         xaxis = list(title = xlabel),
         yaxis = list(title = ylabel))
  
  p
}
```

Rock Gym is composed of two popular rock climbing gyms located in Victoria and Vancouver, British Columbia, that have been operating for 6 years. Use this dashboard to explore peak visit times by hour, day, or month.

```{r}
# plot_ly(data = aggregate(mean_visits ~ membership_type + hour_of_day, data = visits_by_hour, sum),
#         x = ~hour_of_day, 
#         y = ~mean_visits,
#         color = ~membership_type,
#         colors = 'Dark2',
#         hoverinfo = 'text',
#         hovertext = ~paste0(mean_visits, 
#                             " visits on average")
#         ) %>%
#   add_bars() %>%
#   layout(barmode = 'stack',
#          showlegend = F,
#          xaxis = list(title = 'Hour of Day',
#                       categoryorder = "array",
#                       categoryarray = visits_by_hour$hour_of_day),
#          yaxis = list(title = 'Average Customers'))
```


```{r}
# Column {data-width=33%}
# ------------------------------------------------------------------
# 
# ### Filters
# accordion(
#   selected = I("all"),
#   accordion_item(
#     "Sliders",
#     hour_filter,
#     day_filter,
#     month_filter
#   ),
#   accordion_item(
#     "Categories",
#     location_select,
#     membership_type_select
#   )
# )
```

Column {data-width=100% .tabset}
-------------------------------------------------------------------

### By Hour

```{r}
bscols(widths = c(4,8),
       list(
         accordion(
           selected = I("all"),
           accordion_item(
             "Filters",
             hour_filter,
             # location_select,
             # membership_type_select
           )
         ),
         card_grid(card_width = 1/2,
                   card(
                     card_header('Victoria',
                                 class = "bg-success"),
                     card_body(
                       summarywidget(
                         visitsHour,
                         statistic = 'sum',
                         selection = ~location=='Victoria',
                         column = 'mean_visits',
                         digits = 0
                       ),
                       style = 'font-size:26px'
                     ),
                     card_footer('visits per day')
                   ),
                   card(
                     card_header('Vancouver',
                                 class = "bg-warning"),
                     card_body(
                       summarywidget(
                         visitsHour,
                         statistic = 'sum',
                         selection = ~location=='Vancouver',
                         column = 'mean_visits',
                         digits = 0
                       ),
                       style = 'font-size:26px'
                     ),
                     card_footer('visits per day')
                   )
         )
       ),
       average_barplot_by_membership_type(visitsHour,
                                          x_var = 'hour_of_day',
                                          y_var = 'mean_visits',
                                          grouper = 'hour_of_day',
                                          xlabel = "Hour of Day",
                                          ylabel = "Average Customers")
)
```

### By Day
```{r}
bscols(widths = c(4,8),
  list(
    accordion(
      selected = I("all"),
      accordion_item(
        "Filters",
        day_filter,
      )
    ),
    card_grid(card_width = 1/2,
              card(
                card_header('Victoria',
                            class = "bg-success"),
                card_body(
                  summarywidget(
                    visitsDay,
                    statistic = 'sum',
                    selection = ~location=='Victoria',
                    column = 'mean_visits',
                    digits = 0
                  ),
                  style = 'font-size:26px'
                ),
                card_footer('visits per day')
              ),
              card(
                card_header('Vancouver',
                            class = "bg-warning"),
                card_body(
                  summarywidget(
                    visitsDay,
                    statistic = 'sum',
                    selection = ~location=='Vancouver',
                    column = 'mean_visits',
                    digits = 0
                  ),
                  style = 'font-size:26px'
                ),
                card_footer('visits per day')
              )
    )
  ),
  average_barplot_by_membership_type(visitsDay,
                                     x_var = 'day_as_number',
                                     y_var = 'mean_visits',
                                     grouper = 'day_as_number',
                                     xlabel = "Day of Week",
                                     ylabel = "Average Customers")
)
```

### By Month
```{r}
bscols(widths = c(4,8),
       list(
         accordion(
           selected = I("all"),
           accordion_item(
             "Filters",
             month_filter,
           )
         ),
         card_grid(card_width = 1/2,
                   card(
                     card_header('Victoria',
                                 class = "bg-success"),
                     card_body(
                       summarywidget(
                         visitsMonth,
                         statistic = 'sum',
                         selection = ~location=='Victoria',
                         column = 'mean_visits',
                         digits = 0
                       ),
                       style = 'font-size:26px'
                     ),
                     card_footer('visits per day')
                   ),
                   card(
                     card_header('Vancouver',
                                 class = "bg-warning"),
                     card_body(
                       summarywidget(
                         visitsMonth,
                         statistic = 'sum',
                         selection = ~location=='Vancouver',
                         column = 'mean_visits',
                         digits = 0
                       ),
                       style = 'font-size:26px'
                     ),
                     card_footer('visits per day')
                   )
         )
       ),
  average_barplot_by_membership_type(visitsMonth,
                                     x_var = 'month_as_number',
                                     y_var = 'mean_visits',
                                     grouper = 'month_as_number',
                                     xlabel = "Month",
                                     ylabel = "Average Customers")
)
```

```{js}
function filter_default(){
document.getElementById("loc_filter").getElementsByClassName("selectized")[0].selectize.setValue(c("Vancouver"),false) 
document.getElementById("memb_type").getElementsByClassName("selectized")[0].selectize.setValue("Members",false)
}

$(document).ready(filter_default);
```

